# Generated by Django 3.2.4 on 2021-07-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('slug', models.SlugField(max_length=255)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Regular price')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discount price')),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('qty_36', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 36')),
                ('qty_38', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 38')),
                ('qty_40', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 40')),
                ('qty_42', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 42')),
                ('qty_44', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 44')),
                ('qty_46', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 46')),
                ('qty_48', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 48')),
                ('qty_50', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount of size 50')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.category')),
            ],
        ),
    ]
