# Generated by Django 3.2.4 on 2021-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_photo.jpg', upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
    ]
